<?php

/**
 * implements hook_menu
 */

 
 function formul_permission() {
  return array(

      'access formul submissions' => array(
      'title' => t('Acessar formulario'),
      'description' => t('Submit the formul'),
      ),
  );
}

function formul_menu() {
  $items = array();
  
   $items['formul-submissions'] = array(
    'title' => 'Pagina de Formulario',
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('acess formul submissions'),
    'page callback' => 'formul_submissions',
);
  return $items;
}

 
 function formul_theme($existing, $type, $theme, $path) {
  return array(

    'formul_template' => array(
      'variables'=> array(
        'var_one' => NULL,
        'var_two' => NULL,
        'var_three' => NULL,
        'soma_total' => NULL,
        ),
      'template' =>'formul_template',
    ),
    );
}
 
  drupal_add_css(drupal_get_path('module', 'formul') . '/formul.css');
 
/**
 *View the form submissions.
 */
     function formul_submissions(){
     
     for($i=0;$i<16;$i++){
     $resultado = db_query("SELECT data, cid, SUM(data) FROM {webform_submitted_data} WHERE cid=$i  ");
     foreach($resultado as $record){
     }
     // print '<pre>';
     // print_r ($record);
     // print '</pre>';
     
     }

     
      
    for($i=0;$i<16;$i++){
    $result_1 = db_query("SELECT data, cid, SUM(data) FROM {webform_submitted_data} WHERE cid=$i ");
 
    foreach($result_1 as $record){

    $sum[$i][]=$record->data;
    $soma[$i]=array_sum($sum[$i]);
    $var_three=$soma;
   
    }}
    $soma_total=array_sum($soma);
   
      
    $result_2=db_query("SELECT cid, name, pid, weight FROM {webform_component} WHERE pid!=0");
    
    foreach($result_2 as $record){
    $item[$record->weight]=$record->name;
    $var_one=$item;
    }
  

    $result_3=db_query("SELECT cid, name, pid, weight FROM {webform_component}");
 

    foreach($result_3 as $record){
    if($record->pid==0){
    $item_2[$record->weight]=$record->name;
    }
    else if($record->pid!=0){
    $item_2[$record->weight]='&nbsp';
    }
    $var_two=$item_2;
    }
    $var=array_pop($var_two);

   
    return theme('formul_template', array('var_one'=>$var_one,'var_two'=>$var_two,'var_three'=>$var_three,'soma_total'=>$soma_total,));
 }

/**
* Implements hook_entity_info_alter().
*/

/**
 * Implements hook_views_api().
 */
function formul_views_api()
{
    return array(
        'api' => 3,
        'path' => drupal_get_path('module', 'formul'),
    );
}




 
   
